import { Router } from "express";
import AuthRoute from "./auth";
import UsersRoute from "./users";
import AdminsRoute from "./admins";
import PrivilegesRoute from "./privileges";
import CategoryRoute from "./categories";
import PromoCodeRoute from "./promocodes";
import ExtraRoute from "./extras";
import CurrencyRoute from "./currencies";
import ProfileRoute from "./profile";
import HomePageRoute from "./homePage";
import FAQRoute from "./homeFAQ";
import CountryRoute from "./country";
import CityRoute from "./cities";
import PaymentMethodRoute from "./paymentMethods";
import PaymentRoute from "./payments";
import BookingsRoute from "./bookings";
import HomeRoute from "./home";
import TourRoute from "./tours";
import CategoryMedicalRoute from "./medical";
import { authorizePermissions } from "../../middlewares/authorized";
import { authenticated } from "../../middlewares/authenticated";
const router = Router();
router.use("/auth", AuthRoute);
router.use("/users", UsersRoute);
router.use("/admins", AdminsRoute);
router.use("/privileges", PrivilegesRoute);
router.use("/categories", CategoryRoute);
router.use("/promocodes", PromoCodeRoute);
router.use("/currencies", CurrencyRoute);
router.use("/extras", ExtraRoute);
router.use("/homePage", HomePageRoute);
router.use("/faq", FAQRoute);
router.use("/tours", TourRoute);
router.use("/profile", ProfileRoute);
router.use("/country", CountryRoute);
router.use("/city", CityRoute);
router.use("/paymentmethod", PaymentMethodRoute);
router.use("/payments", PaymentRoute);
router.use("/bookings", BookingsRoute);
router.use("/home", HomeRoute);
router.use("/medical", CategoryMedicalRoute);
export default router;
